### PR TITLE
Add 'auto' option for label.anchorX and label.anchorY.

### PR DESCRIPTION
**Pull request by ribrdb**
Fix for issue #240

### CODE REVIEW

**Comment by alfredwassermann** [comment]
Great! Thank you very much.

**Comment by alfredwassermann** [comment]
Do you see a problem with commit 592411747174484e9bc410671041437d60a82f32 ?
I had to restrict anchorX/Y:'auto' to arc amd sector labels. Otherwise there were side effects for slider labels.
Best wishes,
Alfred

**Comment by ribrdb** [comment]
Can you give me an example of the problem you saw?

**Comment by alfredwassermann** [comment]
All slider values were affected:

    var board = JXG.JSXGraph.initBoard('jxgbox1', 
        {boundingbox: [-5, 7, 4.5, -3.5], 
            axis:true, 
            keepaspectratio: true
        });
    var a = board.create('slider',[[-2,6], [3,6], [0.01,1,Math.PI]], {name:'a'});

Best wishes,
Alfred

**Pull request merged**
