### PR TITLE
Added the 'msector' element.

### PR DESCRIPTION
**Pull request by ninmesara**
The 'msector' (or 'm-sector') element, generalizes the bisector.
Instead of dividing an angle into two equal angles, it divides
the angle into two angles of amplitude m and (1-m).

The bisector is the special case in which m = 1/2.
The trisectors of an angle are the special cases in which m = 1/3 and m = 2/3.

This element is interesting because without it there is no way to conveniently
build trisectors, or other general divisions of an angle.
The ability to describe trisectors allows us to illustrate Morley's theorem.

There are two new examples:
- An example of a simple angle trisector
- An example illustrating morley's theorem

### CODE REVIEW

**Comment by Saluev** [comment]
Is it OK that the pull request only contains examples and no implementation?

**Comment by ninmesara** [comment]
No, absolutely not OK. I forgot to add some files to the commit. I'll add them right now. I'm a total git noob, sorry.

Also, I don't really understand jsxgraph's build workflow... For the JSXCompressor folder are we supposed to manually copy bin/jsxgraphcore.js and bin/jsxgraphxore.min.js?

**Comment by ninmesara** [comment]
Don't merge this. I've uncovered what seems to be a bug in the code. I thought I had proved my construction correct but maybe I've made a mistake.

**Comment by alfredwassermann** [comment]
Oh, did not see the last comment and merged the pull request. Can you correct it?
Best wishes,
Alfred

**Comment by ninmesara** [comment]
Yes, I believe I can (but not right now).

On further thought, I probably should change the way the 'msector' element works. Currently, the 'msector' works on the 'nonreflex' angle (that is, the angle that is < 180º). But maybe there should be a 'nonreflexmsector' (which works no the 'nonreflex' angle, just like 'msector' works now) and a 'msector' that will work on the angle, whether it is > 180º or < 180º.

This is a problem we don't have with the 'bisector' element because the bisector is the same in both cases (angle > 180º and angle < 180º).

**Pull request merged**
